from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from collections.abc import Collection
    from uuid import UUID

    from roots_of_rhythm.historical_knowledge.domain import GenreRelationClaim, RecordingOriginClaim


class ClaimRepository(Protocol):
    async def add(self, claim: GenreRelationClaim) -> None: ...
    async def get(self, claim_id: UUID, *, for_update: bool = False) -> GenreRelationClaim | None: ...
    async def save(self, claim: GenreRelationClaim) -> None: ...
    async def mark_deleted(self, claim_id: UUID) -> None: ...
    async def list_by_genre(self, genre_id: UUID) -> list[GenreRelationClaim]: ...


class RecordingOriginClaimRepository(Protocol):
    async def add(self, claim: RecordingOriginClaim) -> None: ...
    async def get(self, claim_id: UUID, *, for_update: bool = False) -> RecordingOriginClaim | None: ...
    async def save(self, claim: RecordingOriginClaim) -> None: ...
    async def mark_deleted(self, claim_id: UUID) -> None: ...
    async def list_supported_published_for_recordings(
        self,
        recording_ids: Collection[UUID],
    ) -> dict[UUID, list[RecordingOriginClaim]]: ...
