from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from uuid import UUID

    from roots_of_rhythm.historical_knowledge.domain import ListeningGuide


class ListeningGuideRepository(Protocol):
    async def add(self, guide: ListeningGuide) -> None: ...
    async def get(self, guide_id: UUID, *, for_update: bool = False) -> ListeningGuide | None: ...
    async def get_published_for_recording(self, recording_id: UUID) -> ListeningGuide | None: ...
    async def save(self, guide: ListeningGuide) -> None: ...
    async def mark_deleted(self, guide_id: UUID) -> None: ...
