from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from collections.abc import Collection
    from uuid import UUID

    from roots_of_rhythm.historical_knowledge.domain import Source, SourceFragment, SourceVersion


class SourceRepository(Protocol):
    async def add_source(self, source: Source) -> None: ...
    async def save_source(self, source: Source) -> None: ...
    async def add_version(self, version: SourceVersion) -> None: ...
    async def add_fragment(self, fragment: SourceFragment) -> None: ...
    async def get_source(self, source_id: UUID, *, for_update: bool = False) -> Source | None: ...
    async def get_sources_by_ids(self, source_ids: Collection[UUID]) -> dict[UUID, Source]: ...
    async def get_version(self, version_id: UUID, *, for_update: bool = False) -> SourceVersion | None: ...
    async def get_versions_by_ids(self, version_ids: Collection[UUID]) -> dict[UUID, SourceVersion]: ...
    async def get_fragment(self, fragment_id: UUID, *, for_update: bool = False) -> SourceFragment | None: ...
    async def get_fragments_by_ids(
        self,
        fragment_ids: Collection[UUID],
        *,
        for_update: bool = False,
    ) -> dict[UUID, SourceFragment]: ...
    async def save_fragment(self, fragment: SourceFragment) -> None: ...
    async def reviewed_source_ids_for_fragments(self, fragment_ids: Collection[UUID]) -> dict[UUID, UUID]: ...
    async def mark_source_deleted(self, source_id: UUID) -> None: ...
    async def mark_version_deleted(self, version_id: UUID) -> None: ...
    async def mark_fragment_deleted(self, fragment_id: UUID) -> None: ...
