from typing import TYPE_CHECKING, Protocol, Self

if TYPE_CHECKING:
    from collections.abc import Collection
    from types import TracebackType
    from uuid import UUID

    from roots_of_rhythm.historical_knowledge.domain import (
        GenreRelationClaim,
        ListeningGuide,
        Source,
        SourceFragment,
        SourceVersion,
    )


class ListeningGuideRepository(Protocol):
    async def add(self, guide: ListeningGuide) -> None: ...
    async def get(self, guide_id: UUID, *, for_update: bool = False) -> ListeningGuide | None: ...
    async def get_published_for_recording(self, recording_id: UUID) -> ListeningGuide | None: ...
    async def save(self, guide: ListeningGuide) -> None: ...
    async def mark_deleted(self, guide_id: UUID) -> None: ...


class ClaimRepository(Protocol):
    async def add(self, claim: GenreRelationClaim) -> None: ...

    async def get(self, claim_id: UUID, *, for_update: bool = False) -> GenreRelationClaim | None: ...

    async def save(self, claim: GenreRelationClaim) -> None: ...

    async def mark_deleted(self, claim_id: UUID) -> None: ...

    async def list_by_genre(self, genre_id: UUID) -> list[GenreRelationClaim]: ...


class SourceRepository(Protocol):
    async def add_source(self, source: Source) -> None: ...

    async def add_version(self, version: SourceVersion) -> None: ...

    async def add_fragment(self, fragment: SourceFragment) -> None: ...

    async def get_source(self, source_id: UUID, *, for_update: bool = False) -> Source | None: ...

    async def get_sources_by_ids(self, source_ids: Collection[UUID]) -> dict[UUID, Source]: ...

    async def get_version(self, version_id: UUID, *, for_update: bool = False) -> SourceVersion | None: ...

    async def get_versions_by_ids(self, version_ids: Collection[UUID]) -> dict[UUID, SourceVersion]: ...

    async def get_fragment(self, fragment_id: UUID, *, for_update: bool = False) -> SourceFragment | None: ...

    async def save_fragment(self, fragment: SourceFragment) -> None: ...

    async def reviewed_source_ids_for_fragments(self, fragment_ids: Collection[UUID]) -> dict[UUID, UUID]: ...

    async def mark_source_deleted(self, source_id: UUID) -> None: ...

    async def mark_version_deleted(self, version_id: UUID) -> None: ...

    async def mark_fragment_deleted(self, fragment_id: UUID) -> None: ...


class HistoricalKnowledgeUnitOfWork(Protocol):
    claims: ClaimRepository
    listening_guides: ListeningGuideRepository
    sources: SourceRepository

    async def __aenter__(self) -> Self: ...

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...
