from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from collections.abc import Collection
    from uuid import UUID

    from roots_of_rhythm.people_catalog.domain import Person


class PersonRepository(Protocol):
    async def add(self, value: Person) -> Person: ...
    async def get(self, id_: UUID, *, for_update: bool = False) -> Person | None: ...
    async def save(self, value: Person) -> Person: ...
    async def mark_deleted(self, id_: UUID) -> None: ...
    async def get_published(self, id_: UUID, *, for_update: bool = False) -> Person | None: ...
    async def get_published_by_ids(self, ids: Collection[UUID], *, for_update: bool = False) -> dict[UUID, Person]: ...
    async def list_published(self) -> tuple[Person, ...]: ...
