/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List published Genres
         * @description Returns identity summaries of all currently published Genres, ordered by canonical name. Draft, archived, and deleted Genres are omitted. An empty list is a successful result.
         */
        get: operations["listPublishedGenres"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/genres/{genre_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a published Genre overview
         * @description Returns the required identity and overview projection. Unknown, malformed, draft, and archived Genre identifiers are intentionally indistinguishable.
         */
        get: operations["getPublishedGenreOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/genres/{genre_id}/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get published relations for a Genre
         * @description Returns all currently visible relation cards as one bounded projection. It does not create one request per Claim.
         */
        get: operations["getPublishedGenreRelations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/genres/{genre_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the public bibliography for a Genre page
         * @description Returns a deduplicated bibliography for all currently public Evidence references used by the Genre page. It does not create one request per Source.
         */
        get: operations["getPublishedGenreSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List published Performers
         * @description Returns identity summaries of all currently published Performers, ordered by canonical name. Draft, archived, and deleted Persons are omitted. An empty list is a successful result.
         */
        get: operations["listPublishedPerformers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performers/{performer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a published Performer overview
         * @description Returns every public Person content field plus primary image and assigned Genres. Editorial status, deleted flags, and timestamps are omitted. Unknown, malformed, draft, and archived identifiers are intentionally indistinguishable.
         */
        get: operations["getPublishedPerformerOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List published Groups
         * @description Returns identity summaries of all currently published Groups, ordered by canonical name. Draft, archived, and deleted Groups are omitted. An empty list is a successful result.
         */
        get: operations["listPublishedGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a published Group overview
         * @description Returns public Group content plus members and assigned Genres. Editorial status, deleted flags, timestamps, evidence, and provenance are omitted. Unknown, malformed, draft, and archived identifiers are intentionally indistinguishable.
         */
        get: operations["getPublishedGroupOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/songs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List published Songs
         * @description Returns identity summaries of all currently published MusicalWorks, ordered by canonical title. Draft, archived, and deleted Works are omitted. An empty list is a successful result.
         */
        get: operations["listPublishedSongs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/songs/{song_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a published Song overview
         * @description Returns public MusicalWork content plus credits, classifications, related Works and rights-aware LyricsVersion projections. Editorial status, deleted flags, timestamps, evidence, and provenance are omitted. Unknown, malformed, draft, and archived identifiers are intentionally indistinguishable.
         */
        get: operations["getPublishedSongOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Stable opaque identifier whose internal format is not a client contract. */
        PublicId: string;
        NullableText: string | null;
        GenreListResponse: {
            /** @description Published Genre summaries ordered by canonical name. */
            items: components["schemas"]["GenreSummary"][];
        };
        GroupListResponse: {
            /** @description Published Group summaries ordered by canonical name. */
            items: components["schemas"]["GroupSummary"][];
        };
        GroupSummary: {
            id: components["schemas"]["PublicId"];
            name: string;
        };
        GroupPeriodView: {
            start: components["schemas"]["TemporalBound"] | null;
            end: components["schemas"]["TemporalBound"] | null;
        };
        GroupMemberView: {
            id: components["schemas"]["PublicId"];
            name: string;
            period: components["schemas"]["GroupPeriodView"];
            /** @description Optional role or instrument labels; may be empty. Not an instrument catalog. */
            roles_or_instruments: string[];
        };
        GroupOverviewResponse: {
            id: components["schemas"]["PublicId"];
            name: string;
            /** @description Alternate names; may be empty. Does not include the canonical name. */
            aliases: string[];
            description: components["schemas"]["NullableText"];
            period: components["schemas"]["GroupPeriodView"];
            primary_image: components["schemas"]["PublicImageView"] | null;
            /** @description Published Genre summaries assigned to the Group, ordered by canonical name. */
            genres: components["schemas"]["GenreSummary"][];
            /** @description Published memberships of published Performers, ordered by person name. */
            members: components["schemas"]["GroupMemberView"][];
        };
        SongListResponse: {
            /** @description Published Song summaries ordered by canonical title. */
            items: components["schemas"]["SongSummary"][];
        };
        SongSummary: {
            id: components["schemas"]["PublicId"];
            name: string;
        };
        SongPeriodView: {
            start: components["schemas"]["TemporalBound"] | null;
            end: components["schemas"]["TemporalBound"] | null;
        };
        SongWorkCreditView: {
            person: components["schemas"]["PerformerSummary"];
            role: components["schemas"]["WorkCreditRole"];
            credited_as: components["schemas"]["NullableText"];
        };
        RelatedWorkView: {
            relation_type: components["schemas"]["WorkRelationType"];
            work: components["schemas"]["SongSummary"];
        };
        LyricsVersionSummary: {
            id: components["schemas"]["PublicId"];
            language_tag: string;
            label: components["schemas"]["NullableText"];
        };
        LyricsVersionRelationView: {
            relation_type: components["schemas"]["LyricsVersionRelationType"];
            version: components["schemas"]["LyricsVersionSummary"];
        };
        SongLyricsVersionView: {
            id: components["schemas"]["PublicId"];
            language_tag: string;
            label: components["schemas"]["NullableText"];
            usage_kind: components["schemas"]["LyricsUsageKind"];
            creation_method: components["schemas"]["LyricsCreationMethod"];
            body: components["schemas"]["NullableText"];
            body_unavailable_reason: components["schemas"]["NullableText"];
            /** @description Published credits with published Performers; may be empty. */
            credits: components["schemas"]["SongWorkCreditView"][];
            /** @description Published relations to other LyricsVersions; may be empty. */
            relations: components["schemas"]["LyricsVersionRelationView"][];
        };
        SongOverviewResponse: {
            id: components["schemas"]["PublicId"];
            name: string;
            /** @description Alternate names; may be empty. Does not include the canonical title. */
            aliases: string[];
            description: components["schemas"]["NullableText"];
            period: components["schemas"]["SongPeriodView"];
            /** @description External catalog identifiers; may be empty. */
            external_identities: components["schemas"]["ExternalIdentityView"][];
            /** @description Published WorkCredits with published Performers; may be empty. */
            credits: components["schemas"]["SongWorkCreditView"][];
            /** @description Published Genre summaries assigned to the Work, ordered by canonical name. */
            classifications: components["schemas"]["GenreSummary"][];
            /** @description Published directed WorkRelations to other published Works; may be empty. */
            related_works: components["schemas"]["RelatedWorkView"][];
            /** @description Published LyricsVersions ordered performable before reading_translation, then language_tag, label, and id. Body is rights-aware. */
            lyrics_versions: components["schemas"]["SongLyricsVersionView"][];
        };
        /** @enum {string} */
        WorkCreditRole: "composer" | "lyricist" | "writer" | "translator" | "adapter" | "arranger" | "other";
        /** @enum {string} */
        WorkRelationType: "translation_of" | "adaptation_of" | "arrangement_of" | "medley_of";
        /** @enum {string} */
        LyricsUsageKind: "performable" | "reading_translation";
        /** @enum {string} */
        LyricsCreationMethod: "original" | "human_translation" | "machine_translation";
        /** @enum {string} */
        LyricsVersionRelationType: "translation_of" | "adaptation_of";
        PerformerListResponse: {
            /** @description Published Performer summaries ordered by canonical name. */
            items: components["schemas"]["PerformerSummary"][];
        };
        PerformerOverviewResponse: {
            id: components["schemas"]["PublicId"];
            name: string;
            /** @description Alternate names; may be empty. Does not include the canonical name. */
            aliases: string[];
            biography: components["schemas"]["NullableText"];
            birth_date: components["schemas"]["TemporalBound"] | null;
            death_date: components["schemas"]["TemporalBound"] | null;
            /** @description External identity records; may be empty. */
            external_identities: components["schemas"]["ExternalIdentityView"][];
            primary_image: components["schemas"]["PublicImageView"] | null;
            /** @description Published Genre summaries assigned to the Performer, ordered by canonical name. */
            genres: components["schemas"]["GenreSummary"][];
        };
        ExternalIdentityView: {
            provider: string;
            identifier: string;
            url: string | null;
        };
        GenreOverviewResponse: {
            id: components["schemas"]["PublicId"];
            name: string;
            definition: string;
            primary_image: components["schemas"]["PublicImageView"] | null;
            period: components["schemas"]["HistoricalPeriodView"] | null;
            geography_or_origin: components["schemas"]["GeographicContextView"] | null;
            historical_context: components["schemas"]["NullableText"];
            formation: components["schemas"]["NullableText"];
            characteristic_features: string[];
        };
        GenreRelationsResponse: {
            genre_id: components["schemas"]["PublicId"];
            /** @description Public relations ordered by temporal start, relation type, and related Genre name. */
            relations: components["schemas"]["GenreRelationView"][];
        };
        GenreSourcesResponse: {
            genre_id: components["schemas"]["PublicId"];
            /** @description Deduplicated bibliography ordered by first public citation occurrence. */
            sources: components["schemas"]["SourceView"][];
        };
        GenreSummary: {
            id: components["schemas"]["PublicId"];
            name: string;
        };
        PerformerSummary: {
            id: components["schemas"]["PublicId"];
            name: string;
        };
        GenreRelationView: {
            id: components["schemas"]["PublicId"];
            related_genre: components["schemas"]["GenreSummary"];
            relation_type: components["schemas"]["GenreRelationType"];
            perspective: components["schemas"]["RelationPerspective"];
            /** @description Explains the relation. For disputed status it must also describe the material disagreement; a generic statement that sources differ is insufficient. */
            explanation: string;
            temporal_context: components["schemas"]["HistoricalPeriodView"];
            geographic_context: components["schemas"]["GeographicContextView"];
            evidence_status: components["schemas"]["EvidenceStatus"];
            /** @description Reviewed public Evidence only; may be empty for unverified. */
            evidence_references: components["schemas"]["EvidenceReferenceView"][];
        };
        /** @enum {string} */
        GenreRelationType: "influenced" | "contributed_to_emergence_of" | "developed_from" | "overlaps_with" | "revival_of";
        /**
         * @description Read-model perspective, not a domain relation type.
         * @enum {string}
         */
        RelationPerspective: "subject" | "target" | "symmetric";
        HistoricalPeriodView: {
            /** @description Editorial wording displayed verbatim by the client. */
            label: string;
            start: components["schemas"]["TemporalBound"] | null;
            end: components["schemas"]["TemporalBound"] | null;
        };
        TemporalBound: {
            /** @description Anchor year interpreted together with precision. */
            year: number;
            precision: components["schemas"]["TemporalPrecision"];
        };
        /** @enum {string} */
        TemporalPrecision: "exact_year" | "circa_year" | "decade" | "early_decade" | "mid_decade" | "late_decade";
        GeographicContextView: {
            summary: string;
        };
        /** @enum {string} */
        EvidenceStatus: "unverified" | "supported" | "disputed";
        /** @enum {string} */
        EvidenceRole: "supports" | "opposes" | "context";
        EvidenceReferenceView: {
            source_id: components["schemas"]["PublicId"];
            role: components["schemas"]["EvidenceRole"];
            locator_text: components["schemas"]["NullableText"];
            external_url: string | null;
        };
        SourceView: {
            id: components["schemas"]["PublicId"];
            title: string;
            author: components["schemas"]["NullableText"];
            responsible_organization: components["schemas"]["NullableText"];
            publication: components["schemas"]["NullableText"];
            publication_date: components["schemas"]["NullableText"];
            external_url: string | null;
        };
        PublicImageView: {
            id: components["schemas"]["PublicId"];
            /** Format: uri */
            url: string;
            alt_text: string;
            width: number | null;
            height: number | null;
            attribution_text: components["schemas"]["NullableText"];
            attribution_url: string | null;
        };
        ErrorResponse: {
            /** @description Stable machine-readable error code. */
            code: string;
            /** @description Safe user-facing message without internal details. */
            message: string;
            details: {
                [key: string]: unknown;
            } | null;
            request_id: components["schemas"]["NullableText"];
        };
    };
    responses: {
        /** @description Genre is absent or not publicly visible. */
        GenreNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "GENRE_NOT_FOUND",
                 *       "message": "Материал не найден.",
                 *       "details": null,
                 *       "request_id": "01K2V3A5J2P9M3EVWQ3E7G4C6X"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Performer is absent or not publicly visible. */
        PerformerNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "PERFORMER_NOT_FOUND",
                 *       "message": "Материал не найден.",
                 *       "details": null,
                 *       "request_id": "01K2V3A5J2P9M3EVWQ3E7G4C6X"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Group is absent or not publicly visible. */
        GroupNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "GROUP_NOT_FOUND",
                 *       "message": "Материал не найден.",
                 *       "details": null,
                 *       "request_id": "01K2V3A5J2P9M3EVWQ3E7G4C6X"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Song is absent or not publicly visible. */
        SongNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "SONG_NOT_FOUND",
                 *       "message": "Материал не найден.",
                 *       "details": null,
                 *       "request_id": "01K2V3A5J2P9M3EVWQ3E7G4C6X"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The requested projection could not be assembled safely. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "INTERNAL_ERROR",
                 *       "message": "Не удалось загрузить материал.",
                 *       "details": null,
                 *       "request_id": "01K2V3A5J2P9M3EVWQ3E7G4C6X"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Stable opaque Genre identifier. Clients must not derive meaning from it. */
        GenreId: components["schemas"]["PublicId"];
        /** @description Stable opaque Performer identifier (Person). Clients must not derive meaning from it. */
        PerformerId: components["schemas"]["PublicId"];
        /** @description Stable opaque Group identifier. Clients must not derive meaning from it. */
        GroupId: components["schemas"]["PublicId"];
        /** @description Stable opaque Song identifier (MusicalWork). Clients must not derive meaning from it. */
        SongId: components["schemas"]["PublicId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPublishedGenres: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered published Genre summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenreListResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getPublishedGenreOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable opaque Genre identifier. Clients must not derive meaning from it. */
                genre_id: components["parameters"]["GenreId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public Genre overview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenreOverviewResponse"];
                };
            };
            404: components["responses"]["GenreNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getPublishedGenreRelations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable opaque Genre identifier. Clients must not derive meaning from it. */
                genre_id: components["parameters"]["GenreId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered public Genre relations; an empty array is a successful result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenreRelationsResponse"];
                };
            };
            404: components["responses"]["GenreNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getPublishedGenreSources: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable opaque Genre identifier. Clients must not derive meaning from it. */
                genre_id: components["parameters"]["GenreId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public Genre bibliography; an empty array is a successful result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenreSourcesResponse"];
                };
            };
            404: components["responses"]["GenreNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listPublishedPerformers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered published Performer summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformerListResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getPublishedPerformerOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable opaque Performer identifier (Person). Clients must not derive meaning from it. */
                performer_id: components["parameters"]["PerformerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public Performer overview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformerOverviewResponse"];
                };
            };
            404: components["responses"]["PerformerNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listPublishedGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered published Group summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupListResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getPublishedGroupOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable opaque Group identifier. Clients must not derive meaning from it. */
                group_id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public Group overview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupOverviewResponse"];
                };
            };
            404: components["responses"]["GroupNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listPublishedSongs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered published Song summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongListResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getPublishedSongOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stable opaque Song identifier (MusicalWork). Clients must not derive meaning from it. */
                song_id: components["parameters"]["SongId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public Song overview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongOverviewResponse"];
                };
            };
            404: components["responses"]["SongNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
}
