from typing import TYPE_CHECKING, Protocol, Self

if TYPE_CHECKING:
    from collections.abc import Collection
    from types import TracebackType
    from uuid import UUID

    from roots_of_rhythm.music_catalog.domain import ClassificationAssignment, Genre, Group, GroupMembership


class GenreRepository(Protocol):
    async def add(self, genre: Genre) -> None: ...

    async def get(self, genre_id: UUID, *, for_update: bool = False) -> Genre | None: ...

    async def get_published(self, genre_id: UUID, *, for_update: bool = False) -> Genre | None: ...

    async def get_published_by_ids(self, genre_ids: Collection[UUID]) -> dict[UUID, Genre]: ...

    async def list_published(self) -> list[Genre]: ...

    async def save(self, genre: Genre) -> None: ...

    async def mark_deleted(self, genre_id: UUID) -> None: ...

    async def published_among(self, genre_ids: Collection[UUID]) -> set[UUID]: ...

    async def canonical_name_exists(self, canonical_name: str, *, excluding: UUID | None = None) -> bool: ...


class ClassificationAssignmentRepository(Protocol):
    async def add(self, assignment: ClassificationAssignment) -> None: ...

    async def get(self, assignment_id: UUID, *, for_update: bool = False) -> ClassificationAssignment | None: ...

    async def list_published_for_person(self, person_id: UUID) -> list[ClassificationAssignment]: ...

    async def list_published_for_group(self, group_id: UUID) -> list[ClassificationAssignment]: ...

    async def save(self, assignment: ClassificationAssignment) -> None: ...


class GroupRepository(Protocol):
    async def add(self, group: Group) -> None: ...

    async def get(self, group_id: UUID, *, for_update: bool = False) -> Group | None: ...

    async def get_published(self, group_id: UUID, *, for_update: bool = False) -> Group | None: ...

    async def list_published(self) -> list[Group]: ...

    async def save(self, group: Group) -> None: ...

    async def mark_deleted(self, group_id: UUID) -> None: ...


class GroupMembershipRepository(Protocol):
    async def add(self, membership: GroupMembership) -> None: ...

    async def get(self, membership_id: UUID, *, for_update: bool = False) -> GroupMembership | None: ...

    async def get_published(self, membership_id: UUID, *, for_update: bool = False) -> GroupMembership | None: ...

    async def list_published_by_group(self, group_id: UUID) -> list[GroupMembership]: ...

    async def save(self, membership: GroupMembership) -> None: ...

    async def mark_deleted(self, membership_id: UUID) -> None: ...


class MusicCatalogUnitOfWork(Protocol):
    genres: GenreRepository
    assignments: ClassificationAssignmentRepository
    groups: GroupRepository
    group_memberships: GroupMembershipRepository

    async def __aenter__(self) -> Self: ...

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...
