from typing import TYPE_CHECKING, Protocol, Self

if TYPE_CHECKING:
    from collections.abc import Collection
    from types import TracebackType
    from uuid import UUID

    from roots_of_rhythm.music_catalog.domain import (
        ClassificationAssignment,
        Genre,
        Group,
        GroupMembership,
        LyricsVersion,
        LyricsVersionCredit,
        LyricsVersionRelation,
        MusicalWork,
        Recording,
        WorkCredit,
        WorkRelation,
    )


class GenreRepository(Protocol):
    async def add(self, genre: Genre) -> None: ...

    async def get(self, genre_id: UUID, *, for_update: bool = False) -> Genre | None: ...

    async def get_published(self, genre_id: UUID, *, for_update: bool = False) -> Genre | None: ...

    async def get_published_by_ids(self, genre_ids: Collection[UUID]) -> dict[UUID, Genre]: ...

    async def list_published(self) -> list[Genre]: ...

    async def save(self, genre: Genre) -> None: ...

    async def mark_deleted(self, genre_id: UUID) -> None: ...

    async def published_among(self, genre_ids: Collection[UUID]) -> set[UUID]: ...

    async def canonical_name_exists(self, canonical_name: str, *, excluding: UUID | None = None) -> bool: ...


class ClassificationAssignmentRepository(Protocol):
    async def add(self, assignment: ClassificationAssignment) -> None: ...

    async def get(self, assignment_id: UUID, *, for_update: bool = False) -> ClassificationAssignment | None: ...

    async def list_published_for_person(self, person_id: UUID) -> list[ClassificationAssignment]: ...

    async def list_published_for_group(self, group_id: UUID) -> list[ClassificationAssignment]: ...

    async def list_published_for_work(self, work_id: UUID) -> list[ClassificationAssignment]: ...

    async def list_published_for_recording(self, recording_id: UUID) -> list[ClassificationAssignment]: ...

    async def save(self, assignment: ClassificationAssignment) -> None: ...


class GroupRepository(Protocol):
    async def add(self, group: Group) -> None: ...

    async def get(self, group_id: UUID, *, for_update: bool = False) -> Group | None: ...

    async def get_published(self, group_id: UUID, *, for_update: bool = False) -> Group | None: ...

    async def get_published_by_ids(self, group_ids: Collection[UUID]) -> dict[UUID, Group]: ...

    async def list_published(self) -> list[Group]: ...

    async def save(self, group: Group) -> None: ...

    async def mark_deleted(self, group_id: UUID) -> None: ...


class GroupMembershipRepository(Protocol):
    async def add(self, membership: GroupMembership) -> None: ...

    async def get(self, membership_id: UUID, *, for_update: bool = False) -> GroupMembership | None: ...

    async def get_published(self, membership_id: UUID, *, for_update: bool = False) -> GroupMembership | None: ...

    async def list_published_by_group(self, group_id: UUID) -> list[GroupMembership]: ...

    async def save(self, membership: GroupMembership) -> None: ...

    async def mark_deleted(self, membership_id: UUID) -> None: ...


class MusicalWorkRepository(Protocol):
    async def add(self, work: MusicalWork) -> None: ...

    async def get(self, work_id: UUID, *, for_update: bool = False) -> MusicalWork | None: ...

    async def get_published(self, work_id: UUID, *, for_update: bool = False) -> MusicalWork | None: ...

    async def get_published_by_ids(self, work_ids: Collection[UUID]) -> dict[UUID, MusicalWork]: ...

    async def list_published(self) -> list[MusicalWork]: ...

    async def save(self, work: MusicalWork) -> None: ...

    async def mark_deleted(self, work_id: UUID) -> None: ...


class WorkCreditRepository(Protocol):
    async def add(self, credit: WorkCredit) -> None: ...

    async def get(self, credit_id: UUID, *, for_update: bool = False) -> WorkCredit | None: ...

    async def get_published(self, credit_id: UUID, *, for_update: bool = False) -> WorkCredit | None: ...

    async def list_published_for_work(self, work_id: UUID) -> list[WorkCredit]: ...

    async def save(self, credit: WorkCredit) -> None: ...

    async def mark_deleted(self, credit_id: UUID) -> None: ...


class WorkRelationRepository(Protocol):
    async def add(self, relation: WorkRelation) -> None: ...

    async def get(self, relation_id: UUID, *, for_update: bool = False) -> WorkRelation | None: ...

    async def get_published(self, relation_id: UUID, *, for_update: bool = False) -> WorkRelation | None: ...

    async def list_published_for_work(self, work_id: UUID) -> list[WorkRelation]: ...

    async def save(self, relation: WorkRelation) -> None: ...

    async def mark_deleted(self, relation_id: UUID) -> None: ...


class LyricsVersionRepository(Protocol):
    async def add(self, version: LyricsVersion) -> None: ...

    async def get(self, version_id: UUID, *, for_update: bool = False) -> LyricsVersion | None: ...

    async def get_published(self, version_id: UUID, *, for_update: bool = False) -> LyricsVersion | None: ...

    async def get_published_by_ids(self, version_ids: Collection[UUID]) -> dict[UUID, LyricsVersion]: ...

    async def list_published_for_work(self, work_id: UUID) -> list[LyricsVersion]: ...

    async def save(self, version: LyricsVersion) -> None: ...

    async def mark_deleted(self, version_id: UUID) -> None: ...


class LyricsVersionCreditRepository(Protocol):
    async def add(self, credit: LyricsVersionCredit) -> None: ...

    async def get(self, credit_id: UUID, *, for_update: bool = False) -> LyricsVersionCredit | None: ...

    async def get_published(self, credit_id: UUID, *, for_update: bool = False) -> LyricsVersionCredit | None: ...

    async def list_published_for_version(self, lyrics_version_id: UUID) -> list[LyricsVersionCredit]: ...

    async def list_published_for_versions(
        self,
        lyrics_version_ids: Collection[UUID],
    ) -> dict[UUID, list[LyricsVersionCredit]]: ...

    async def save(self, credit: LyricsVersionCredit) -> None: ...

    async def mark_deleted(self, credit_id: UUID) -> None: ...


class LyricsVersionRelationRepository(Protocol):
    async def add(self, relation: LyricsVersionRelation) -> None: ...

    async def get(self, relation_id: UUID, *, for_update: bool = False) -> LyricsVersionRelation | None: ...

    async def get_published(self, relation_id: UUID, *, for_update: bool = False) -> LyricsVersionRelation | None: ...

    async def list_published_for_version(self, lyrics_version_id: UUID) -> list[LyricsVersionRelation]: ...

    async def list_published_for_versions(
        self,
        lyrics_version_ids: Collection[UUID],
    ) -> dict[UUID, list[LyricsVersionRelation]]: ...

    async def save(self, relation: LyricsVersionRelation) -> None: ...

    async def mark_deleted(self, relation_id: UUID) -> None: ...


class RecordingRepository(Protocol):
    async def add(self, recording: Recording) -> None: ...

    async def get(self, recording_id: UUID, *, for_update: bool = False) -> Recording | None: ...

    async def get_published(self, recording_id: UUID, *, for_update: bool = False) -> Recording | None: ...

    async def save(self, recording: Recording) -> None: ...

    async def save_status(self, recording: Recording) -> None: ...

    async def mark_deleted(self, recording_id: UUID) -> None: ...


class MusicCatalogUnitOfWork(Protocol):
    genres: GenreRepository
    assignments: ClassificationAssignmentRepository
    groups: GroupRepository
    group_memberships: GroupMembershipRepository
    works: MusicalWorkRepository
    work_credits: WorkCreditRepository
    work_relations: WorkRelationRepository
    lyrics_versions: LyricsVersionRepository
    lyrics_version_credits: LyricsVersionCreditRepository
    lyrics_version_relations: LyricsVersionRelationRepository

    async def __aenter__(self) -> Self: ...

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...


class RecordingUnitOfWork(MusicCatalogUnitOfWork, Protocol):
    recordings: RecordingRepository
